### PR TITLE
Use HarfBuzz to draw glyphs from binary fonts

### PR DESCRIPTION
**Pull request by khaledhosny**
Drops FreeType dependency. The initial goal was to drop `makePathFromOutline.m` and simplify things, but `makePathFromArrays()` is still used by `dsFont` module and I kept it unchanged as I don’t know if there is a reason not to use `CocoaPen` here too.

Might be a good idea to also cache the glyph outlines, but old code did not do that.

### CODE REVIEW

**Comment by justvanrossum** [comment]
The reason that .m file exists is performance. I know it's a burden and it's not well factored, but freetype + that .m code allows to construct NSBezierPath objects at C speed, which makes FontGoggles behave reasonably fast even with very complex outlines. I doubt this PR maintains that performance.

(I can privately send you a crazy experimental variable TTF if you want to compare responsiveness, especially when playing with VF axis sliders.)

**Comment by khaledhosny** [comment]
Sure, please send me the font. I agree performance should be prioritized and if this PR makes things slow then I’m fine closing it.

**Comment by justvanrossum** [comment]
What is a good email address for you? I am my github user name at gmail.

**Comment by khaledhosny** [comment]
Thanks @justvanrossum for sharing the file with me. I tested but couldn’t feel any difference in the UI, so I wrote a small script to load the font then `getGlyphRun()` multiple times with different locations, and wow this PR is over 70 times slower than master!

Master:
```
         20569 function calls (20546 primitive calls) in 0.084 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      7/1    0.000    0.000    0.084    0.084 {built-in method builtins.exec}
        1    0.001    0.001    0.084    0.084 a.py:8(test)
        1    0.000    0.000    0.084    0.084 <string>:1(<module>)
      144    0.001    0.000    0.080    0.001 baseFont.py:132(getGlyphRun)
      864    0.001    0.000    0.072    0.000 baseFont.py:153(getGlyphDrawings)
      552    0.001    0.000    0.071    0.000 otfFont.py:13(_getGlyphDrawing)
      552    0.001    0.000    0.071    0.000 ftFont.py:66(getOutlinePath)
      552    0.040    0.000    0.040    0.000 makePathFromOutline.py:44(makePathFromOutline)
      552    0.028    0.000    0.028    0.000 __init__.py:1398(load_glyph)
      144    0.000    0.000    0.004    0.000 baseFont.py:143(setVarLocation)
      144    0.002    0.000    0.003    0.000 hbShape.py:156(shape)
      138    0.000    0.000    0.003    0.000 otfFont.py:24(varLocationChanged)
      140    0.000    0.000    0.003    0.000 ttFont.py:369(__getitem__)
      138    0.001    0.000    0.003    0.000 ftFont.py:29(setVarLocation)
      151    0.000    0.000    0.003    0.000 properties.py:36(__get__)
        1    0.000    0.000    0.003    0.003 baseFont.py:78(axes)
      4/3    0.000    0.000    0.002    0.001 {built-in method builtins.__import__}
      6/3    0.000    0.000    0.002    0.001 <frozen importlib._bootstrap>:978(_find_and_load)
      6/3    0.000    0.000    0.002    0.001 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
        2    0.000    0.000    0.002    0.001 ttFont.py:833(getTableClass)
        2    0.000    0.000    0.002    0.001 ttFont.py:812(getTableModule)
      6/3    0.000    0.000    0.002    0.001 <frozen importlib._bootstrap>:663(_load_unlocked)
      6/3    0.000    0.000    0.002    0.001 <frozen importlib._bootstrap_external>:722(exec_module)
      7/3    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
        1    0.000    0.000    0.001    0.001 _n_a_m_e.py:2(<module>)
        6    0.000    0.000    0.001    0.000 <frozen importlib._bootstrap_external>:793(get_code)
      552    0.001    0.000    0.001    0.000 ttFont.py:564(getGlyphID)
      552    0.001    0.000    0.001    0.000 __init__.py:1937(_get_glyph)
        1    0.000    0.000    0.001    0.001 ttFont.py:422(get)
      144    0.001    0.000    0.001    0.000 {uharfbuzz._harfbuzz.shape}
        1    0.000    0.000    0.001    0.001 encodingTools.py:2(<module>)
      ...
```

This PR:
```
         4942280 function calls (4942232 primitive calls) in 6.203 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      7/1    0.000    0.000    6.203    6.203 {built-in method builtins.exec}
        1    0.000    0.000    6.203    6.203 <string>:1(<module>)
        1    0.001    0.001    6.203    6.203 a.py:8(test)
      144    0.001    0.000    6.198    0.043 baseFont.py:132(getGlyphRun)
      864    0.001    0.000    6.191    0.007 baseFont.py:153(getGlyphDrawings)
      552    0.001    0.000    6.190    0.011 otfFont.py:18(_getGlyphDrawing)
      552    0.001    0.000    6.189    0.011 otfFont.py:13(_getGlyphOutline)
      552    0.452    0.001    6.180    0.011 {method 'draw_glyph_with_pen' of 'uharfbuzz._harfbuzz.Font' objects}
   702843    0.666    0.000    5.714    0.000 basePen.py:285(qCurveTo)
   702843    0.565    0.000    4.418    0.000 basePen.py:218(_qCurveToOne)
   702843    3.853    0.000    3.853    0.000 cocoaPen.py:23(_curveToOne)
   702843    0.477    0.000    0.575    0.000 basePen.py:348(decomposeQuadraticSegment)
1405864/1405857    0.098    0.000    0.098    0.000 {built-in method builtins.len}
   703786    0.056    0.000    0.056    0.000 {method 'append' of 'list' objects}
      552    0.005    0.000    0.008    0.000 cocoaPen.py:10(__init__)
     1656    0.001    0.000    0.007    0.000 basePen.py:252(lineTo)
     1656    0.006    0.000    0.006    0.000 cocoaPen.py:20(_lineTo)
      151    0.000    0.000    0.005    0.000 properties.py:36(__get__)
      828    0.001    0.000    0.005    0.000 basePen.py:248(moveTo)
        1    0.000    0.000    0.005    0.005 baseFont.py:78(axes)
      144    0.002    0.000    0.004    0.000 hbShape.py:157(shape)
      828    0.004    0.000    0.004    0.000 cocoaPen.py:17(_moveTo)
      4/3    0.000    0.000    0.004    0.001 {built-in method builtins.__import__}
      6/3    0.000    0.000    0.004    0.001 <frozen importlib._bootstrap>:978(_find_and_load)
        2    0.000    0.000    0.004    0.002 ttFont.py:369(__getitem__)
      6/3    0.000    0.000    0.004    0.001 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
      6/3    0.000    0.000    0.004    0.001 <frozen importlib._bootstrap>:663(_load_unlocked)
      6/3    0.000    0.000    0.004    0.001 <frozen importlib._bootstrap_external>:722(exec_module)
        2    0.000    0.000    0.003    0.002 ttFont.py:833(getTableClass)
        2    0.000    0.000    0.003    0.002 ttFont.py:812(getTableModule)
        6    0.000    0.000    0.002    0.000 <frozen importlib._bootstrap_external>:793(get_code)
      7/3    0.000    0.000    0.002    0.001 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
      828    0.000    0.000    0.002    0.000 basePen.py:240(closePath)
        1    0.000    0.000    0.002    0.002 _n_a_m_e.py:2(<module>)
        6    0.000    0.000    0.002    0.000 <frozen importlib._bootstrap_external>:914(get_data)
      570    0.001    0.000    0.002    0.000 <frozen importlib._bootstrap>:1009(_handle_fromlist)
      828    0.001    0.000    0.001    0.000 cocoaPen.py:26(_closePath)
        6    0.001    0.000    0.001    0.000 {method 'read' of '_io.FileIO' objects}
      144    0.000    0.000    0.001    0.000 baseFont.py:143(setVarLocation)
      552    0.001    0.000    0.001    0.000 basePen.py:195(__init__)
        1    0.000    0.000    0.001    0.001 ttFont.py:422(get)
        1    0.000    0.000    0.001    0.001 encodingTools.py:2(<module>)
      144    0.001    0.000    0.001    0.000 {uharfbuzz._harfbuzz.shape}
     1150    0.000    0.000    0.001    0.000 {built-in method builtins.hasattr}
        6    0.000    0.000    0.001    0.000 _n_a_m_e.py:413(__str__)
      ...
```

**Comment by justvanrossum** [comment]
Thanks for checking this so thoroughly! I'm glad to have independent confirmation that me torturing myself with C and Objective C had some net benefit...

Function/method calls are notoriously expensive in Python, and there are many of them in the inner loop when drawing (complex) outlines. There are at least two layers here: calling the pen methods from uharfbuzz, and calling the NSBezierPath methods via the PyObjC bridge. The latter probably adds significant overhead, too.

Getting rid of the FreeType dependency in favor of the HB-based outline extraction would not be a bad thing, if we could similarly do that in C: ensuring there's no Python code between the HB draw callbacks and the NSBezierPath methods. I'm not sure it's worth the effort at this time, though, especially since I'm not bothered too much by the FT dependency.

Either way, the factoring of the FG outline building stuff is definitely sub-optimal. See also #73.

**Comment by khaledhosny** [comment]
> I'm not bothered too much by the FT dependency.

Yes, it isn’t FreeType dependency that is bothering me, but the added complexity of having a C library, but it is now clear that there is no way around it.

For future reference, here is the simple code I used for profiling:
```python
import asyncio
import cProfile
import pathlib
import sys

from fontgoggles.font import getOpener

pr = cProfile.Profile()


def test(font, text):
    for tag1, axis1 in font.axes.items():
        for tag2, axis2 in font.axes.items():
            location = {tag1: axis1["minValue"], tag2: axis2["minValue"]}
            run = font.getGlyphRun(text, varLocation=location)
            location = {tag1: axis1["maxValue"], tag2: axis2["maxValue"]}
            run = font.getGlyphRun(text, varLocation=location)
            location = {tag1: axis1["minValue"], tag2: axis2["maxValue"]}
            run = font.getGlyphRun(text, varLocation=location)
            location = {tag1: axis1["maxValue"], tag2: axis2["minValue"]}
            run = font.getGlyphRun(text, varLocation=location)


async def main():
    fontPath = pathlib.Path(sys.argv[1])
    text = sys.argv[2]
    numFonts, opener, getSortInfo = getOpener(fontPath)
    font = opener(fontPath, 0)
    await font.load(None)
    pr.enable()
    test(font, text)
    pr.disable()


asyncio.run(main())
pr.print_stats(sort="cumtime")
```

**Comment by khaledhosny** [comment]
Since there seems to be a renewed interest in using HarfBuzz for drawing to test experimental extensions. Would a version if this PR that uses the current code by default but has an option to use hb-draw be accepted?

**Comment by khaledhosny** [comment]
Alternatively, we can look into using HarfBuzz C API directly, or adding support to uharfbuzz to draw in a performant way without using pens.

**Comment by justvanrossum** [comment]
It would be absolutely great if we can use the HarfBuzz C API directly. That way we can drop FreeType without losing performance.

I would be OK writing the needed C code, but at this point I don't know how to link to the harfbuzz library embedded in the uharfbuzz extension.

**Comment by justvanrossum** [comment]
I have opened #267 for further discussion.

**Pull request closed without merging**
