### PR TITLE
App icon proposal

### PR DESCRIPTION
**Pull request by Zabriskije**
Hey Just, since the current app icon is not in line with Apple's HIG and as a thank you for making FontGoggles, I've made a new app icon that can also work as a logo.

I've made two variations: one black and one with the same gradient used in the App Store and other macOS icons:

 

I prefer the black one, but I'll leave the decision to you.

I've also changed the icon in the `README.md` to reflect that and added an SVG in `App/Resources` in case you want to use it somewhere else.

### CODE REVIEW

**Comment by justvanrossum** [comment]
Can you elaborate as to why the current icon wouldn’t be in line with Apple’s HIG?

**Comment by justvanrossum** [comment]
Either way, thank you, but no thanks.

**Comment by Zabriskije** [comment]
> Can you elaborate as to why the current icon wouldn’t be in line with Apple’s HIG?

From [Apple's HIG → App Icons → Platform considerations → macOS](https://developer.apple.com/design/human-interface-guidelines/app-icons#macOS):

- In macOS, app icons share a common set of visual attributes, including a rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow. Rooted in the macOS design language, these attributes showcase the lifelike rendering style people expect in macOS while presenting a harmonious user experience. [...] Avoid defining contours that suggest a shape other than a rounded rectangle. In rare cases, you might want to fine-tune the basic app icon shape, but doing so risks creating an icon that looks like it doesn’t belong in macOS. If you must alter the shape, prefer subtle adjustments that continue to express a rounded rectangle silhouette.

May I ask you what you didn't like about the icons?

**Comment by justvanrossum** [comment]
FontGoggles has been out since early 2020, and is quite widely used among font developers. It would be confusing (if not outright silly) to radically change the icon at this point.

What I like about the current icon:
- it functions well at most sizes
- it is very recognizable
- it uses a great typeface
- it uses pleasant, expressive colors

I don't think Apple's HIG are holy. They are _guidelines_, not strict rules.

All in all there is zero need for a new icon, regardless of what I may think of your design.

**Pull request closed without merging**
